<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "course_scheduler"
 *
 * Auto generated by Extension Builder 2020-06-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Weekly Course Scheduler',
    'description' => 'Show recurring courses in a weekly scheduler',
    'category' => 'plugin',
    'author' => 'Gerald Rintisch',
    'author_email' => 'gerald.rintisch@posteo.de',
    'state' => 'stable',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],    
    'version' => '1.0.0',
];
